//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace MWMS.UserFramework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 用户
	/// </summary>
	public class User
	{
		public virtual float Id
		{
			get;
			set;
		}

		public virtual string UserName
		{
			get;
			set;
		}

		public virtual string Mobile
		{
			get;
			set;
		}

		public virtual void EditPassword(object oldPassword, object newPassword)
		{
			throw new System.NotImplementedException();
		}

	}
}

