//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UserFramework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 公用类
	/// </summary>
	public abstract class Common
	{
		/// <summary>
		/// 加密
		/// </summary>
		/// <param name="str">字符串</param>
		public static string Encryption(object str)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 解密
		/// </summary>
		/// <param name="str">字符串</param>
		public static string Decrypt(object str)
		{
			throw new System.NotImplementedException();
		}

	}
}

