//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UserFramework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 登录
	/// </summary>
	public class Login
	{
		/// <summary>
		/// 登录用户
		/// </summary>
		public object User
		{
			get;
			set;
		}

		/// <summary>
		/// 登录钥匙
		/// </summary>
		public string Token
		{
			get;
			set;
		}

		/// <summary>
		/// 是否为管理员
		/// </summary>
		public object IsAdministrator
		{
			get;
			set;
		}

		/// <summary>
		/// 退出
		/// </summary>
		public void Exit()
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 用户名密码登录
		/// </summary>
		/// <param name="username">用户名</param>
		/// <param name="password">密码</param>
		public Login(string username, string password)
		{
		}

		/// <summary>
		/// token登录
		/// </summary>
		public Login(string token)
		{
		}

	}
}

