//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace UserFramework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 注册
	/// </summary>
	public class Reg
	{
		/// <summary>
		/// 注册
		/// </summary>
		/// <param name="username">用户名</param>
		/// <param name="password">密码</param>
		/// <param name="customFields">自定义字段</param>
		public Reg(string username, string password, object customFields)
		{
		}

	}
}

